"""Built-in method presets — 7 planning method configs seeded into the database."""

PRESETS: list[dict] = [
    # ======================== 1. Ivy Lee Method ========================
    {
        "slug": "ivy-lee",
        "name": "Ivy Lee Method",
        "name_zh": "\u827e\u7dad\u00b7\u674e\u6cd5",
        "icon": "\U0001f4dd",
        "color": "#cba6f7",
        "layout_type": "list",
        "is_preset": True,
        "tags": ["focus", "simplicity", "classic"],
        "config": {
            "max_items": 6,
            "categories": [],
            "ordering": "sequential",
            "sequential_strict": True,
            "frog": {"enabled": False},
            "time_awareness": {"enabled": False, "mode": "none"},
            "review_cycle": {
                "morning_review": {"enabled": False},
                "evening_review": {
                    "enabled": True,
                    "default_time": "21:00",
                    "prompt": "Review today and prepare tomorrow's 6 tasks",
                    "prompt_zh": "\u56de\u9867\u4eca\u65e5\uff0c\u6e96\u5099\u660e\u5929\u6700\u91cd\u8981\u7684 6 \u4ef6\u4e8b",  # noqa: E501
                },
                "weekly_review": {"enabled": False},
            },
            "completion_rule": {
                "mode": "all",
                "threshold": 1.0,
                "frog_required": False,
                "streak_tracking": True,
                "celebration": {
                    "on_day_complete": "All 6 done! Perfect day.",
                    "on_streak_milestone": "{n}-day streak!",
                },
            },
            "overflow": {
                "mode": "carry_forward",
                "max_carry_days": 2,
                "carry_limit": None,
                "stale_warning_days": 2,
            },
            "item_sources": {
                "taskflow": {
                    "enabled": True,
                    "auto_include_due_today": True,
                    "auto_include_overdue": True,
                },
                "finance": {"enabled": False},
                "invest": {"enabled": False},
                "briefing": {"enabled": False},
                "capture": {"enabled": False},
            },
            "ui_hints": {
                "show_numbers": True,
                "show_category_headers": False,
                "show_progress_bar": True,
                "show_time_column": False,
                "show_frog_badge": False,
                "empty_state_message_zh": "\u9078\u51fa\u4eca\u5929\u6700\u91cd\u8981\u7684 6 \u4ef6\u4e8b\uff0c\u6309\u91cd\u8981\u6027\u6392\u5e8f\u3002",  # noqa: E501
                "compact_mode": False,
            },
        },
    },
    # ======================== 2. 1-3-5 Rule ========================
    {
        "slug": "one-three-five",
        "name": "1-3-5 Rule",
        "name_zh": "1-3-5 \u6cd5\u5247",
        "icon": "\U0001f3af",
        "color": "#89b4fa",
        "layout_type": "columns",
        "is_preset": True,
        "tags": ["balanced", "structured", "popular"],
        "config": {
            "max_items": 9,
            "categories": [
                {
                    "id": "big",
                    "name": "Big Task",
                    "name_zh": "\u91cd\u8981\u4efb\u52d9",
                    "icon": "\U0001f3af",
                    "color": "#f38ba8",
                    "max_items": 1,
                    "min_items": 1,
                    "sort_order": 0,
                    "priority_weight": 3,
                    "accept_filter": {"priority": ["urgent", "high"]},
                },
                {
                    "id": "medium",
                    "name": "Medium Tasks",
                    "name_zh": "\u4e2d\u578b\u4efb\u52d9",
                    "icon": "\U0001f4cb",
                    "color": "#89b4fa",
                    "max_items": 3,
                    "min_items": 0,
                    "sort_order": 1,
                    "priority_weight": 2,
                    "accept_filter": {"priority": ["high", "medium"]},
                },
                {
                    "id": "small",
                    "name": "Small Tasks",
                    "name_zh": "\u5c0f\u4efb\u52d9",
                    "icon": "\u270f\ufe0f",
                    "color": "#a6e3a1",
                    "max_items": 5,
                    "min_items": 0,
                    "sort_order": 2,
                    "priority_weight": 1,
                    "accept_filter": {"estimated_hours_lte": 0.5},
                },
            ],
            "ordering": "category",
            "sequential_strict": False,
            "frog": {"enabled": False},
            "time_awareness": {"enabled": False, "mode": "estimates"},
            "review_cycle": {
                "morning_review": {
                    "enabled": True,
                    "default_time": "08:30",
                    "prompt_zh": "\u78ba\u8a8d\u4eca\u65e5 1-3-5 \u914d\u7f6e",
                },
                "evening_review": {
                    "enabled": True,
                    "default_time": "21:00",
                    "prompt_zh": "\u56de\u9867\u5b8c\u6210\u5ea6\uff0c\u8abf\u6574\u660e\u65e5\u8a08\u756b",  # noqa: E501
                },
                "weekly_review": {"enabled": False},
            },
            "completion_rule": {
                "mode": "weighted",
                "threshold": 0.7,
                "frog_required": False,
                "streak_tracking": True,
                "celebration": {"on_day_complete": "1-3-5 achieved!"},
            },
            "overflow": {
                "mode": "review_then_decide",
                "max_carry_days": 3,
                "stale_warning_days": 2,
            },
            "item_sources": {
                "taskflow": {
                    "enabled": True,
                    "auto_include_due_today": True,
                    "auto_include_overdue": True,
                },
                "finance": {"enabled": True, "include_types": ["subscription_due"]},
                "invest": {"enabled": False},
                "briefing": {"enabled": True, "include_types": ["daily_briefing"]},
                "capture": {"enabled": True, "include_types": ["pending_captures"]},
            },
            "ui_hints": {
                "show_numbers": False,
                "show_category_headers": True,
                "show_progress_bar": True,
                "show_time_column": False,
                "show_frog_badge": False,
                "empty_state_message_zh": "\u898f\u5283\u4eca\u65e5\uff1a1 \u4ef6\u5927\u4e8b\u30013 \u4ef6\u4e2d\u4e8b\u30015 \u4ef6\u5c0f\u4e8b\u3002",  # noqa: E501
                "compact_mode": False,
            },
        },
    },
    # ======================== 3. Eat the Frog ========================
    {
        "slug": "eat-the-frog",
        "name": "Eat the Frog",
        "name_zh": "\u5403\u6389\u90a3\u96bb\u9752\u86d9",
        "icon": "\U0001f438",
        "color": "#a6e3a1",
        "layout_type": "list",
        "is_preset": True,
        "tags": ["focus", "procrastination", "morning"],
        "config": {
            "max_items": None,
            "categories": [],
            "ordering": "priority",
            "sequential_strict": False,
            "frog": {
                "enabled": True,
                "count": 1,
                "label": "Frog",
                "label_zh": "\u9752\u86d9",
                "icon": "\U0001f438",
                "auto_suggest": True,
                "suggest_criteria": {
                    "prefer_high_priority": True,
                    "prefer_dreaded": True,
                    "prefer_high_impact": True,
                    "max_age_days": 7,
                },
                "must_do_first": True,
            },
            "time_awareness": {"enabled": False, "mode": "none"},
            "review_cycle": {
                "morning_review": {
                    "enabled": True,
                    "default_time": "07:00",
                    "prompt_zh": "\u627e\u51fa\u4eca\u5929\u7684\u9752\u86d9\uff0c\u5148\u5403\u6389\u5b83",  # noqa: E501
                },
                "evening_review": {
                    "enabled": True,
                    "default_time": "21:00",
                    "prompt_zh": "\u9752\u86d9\u5403\u4e86\u55ce\uff1f\u660e\u5929\u7684\u9752\u86d9\u662f\u4ec0\u9ebc\uff1f",  # noqa: E501
                },
                "weekly_review": {"enabled": False},
            },
            "completion_rule": {
                "mode": "frog_plus_percentage",
                "threshold": 0.6,
                "frog_required": True,
                "streak_tracking": True,
                "celebration": {
                    "on_frog_done": "Frog eaten! The rest of the day is yours.",
                    "on_day_complete": "All done! Legendary day.",
                },
            },
            "overflow": {
                "mode": "carry_forward",
                "max_carry_days": None,
                "stale_warning_days": 3,
            },
            "item_sources": {
                "taskflow": {
                    "enabled": True,
                    "auto_include_due_today": True,
                    "auto_include_overdue": True,
                },
                "finance": {"enabled": False},
                "invest": {"enabled": False},
                "briefing": {"enabled": False},
                "capture": {"enabled": False},
            },
            "ui_hints": {
                "show_numbers": False,
                "show_category_headers": False,
                "show_progress_bar": True,
                "show_time_column": False,
                "show_frog_badge": True,
                "empty_state_message_zh": "\u9078\u51fa\u4f60\u6700\u4e0d\u60f3\u505a\u4f46\u6700\u91cd\u8981\u7684\u90a3\u4ef6\u4e8b\u3002\u5148\u641e\u5b9a\u5b83\u3002",  # noqa: E501
                "compact_mode": False,
            },
        },
    },
    # ======================== 4. Time Blocking ========================
    {
        "slug": "time-blocking",
        "name": "Time Blocking",
        "name_zh": "\u6642\u9593\u5340\u584a\u6cd5",
        "icon": "\U0001f550",
        "color": "#fab387",
        "layout_type": "timeline",
        "is_preset": True,
        "tags": ["time-management", "calendar", "structured"],
        "config": {
            "max_items": None,
            "categories": [],
            "ordering": "time",
            "sequential_strict": False,
            "frog": {"enabled": False},
            "time_awareness": {
                "enabled": True,
                "mode": "blocks",
                "day_start": "09:00",
                "day_end": "18:00",
                "slot_duration_minutes": 30,
                "include_breaks": True,
                "break_pattern": {"work_minutes": 90, "break_minutes": 15},
                "pomodoro": None,
            },
            "review_cycle": {
                "morning_review": {
                    "enabled": True,
                    "default_time": "08:30",
                    "prompt_zh": "\u5b89\u6392\u4eca\u65e5\u6642\u9593\u5340\u584a",
                },
                "evening_review": {
                    "enabled": True,
                    "default_time": "18:30",
                    "prompt_zh": "\u56de\u9867\u6642\u9593\u4f7f\u7528\uff0c\u512a\u5316\u660e\u65e5\u5b89\u6392",  # noqa: E501
                },
                "weekly_review": {
                    "enabled": True,
                    "day_of_week": 0,
                    "prompt": "Review time allocation patterns",
                },
            },
            "completion_rule": {
                "mode": "percentage",
                "threshold": 0.75,
                "frog_required": False,
                "streak_tracking": True,
                "celebration": {"on_day_complete": "All blocks completed!"},
            },
            "overflow": {
                "mode": "review_then_decide",
                "max_carry_days": 1,
                "carry_limit": 3,
                "stale_warning_days": 1,
            },
            "item_sources": {
                "taskflow": {
                    "enabled": True,
                    "auto_include_due_today": True,
                    "auto_include_overdue": True,
                },
                "finance": {
                    "enabled": True,
                    "include_types": ["subscription_due", "budget_review"],
                },
                "invest": {"enabled": True, "include_types": ["portfolio_review"]},
                "briefing": {"enabled": True, "include_types": ["daily_briefing"]},
                "capture": {"enabled": True, "include_types": ["pending_captures"]},
            },
            "ui_hints": {
                "show_numbers": False,
                "show_category_headers": False,
                "show_progress_bar": True,
                "show_time_column": True,
                "show_frog_badge": False,
                "empty_state_message_zh": "\u5c07\u4efb\u52d9\u62d6\u5165\u6642\u9593\u8ef8\uff0c\u898f\u5283\u4f60\u7684\u4e00\u5929\u3002",  # noqa: E501
                "compact_mode": False,
            },
        },
    },
    # ======================== 5. Eisenhower Matrix ========================
    {
        "slug": "eisenhower",
        "name": "Eisenhower Matrix",
        "name_zh": "\u827e\u68ee\u8c6a\u77e9\u9663",
        "icon": "\U0001f396\ufe0f",
        "color": "#f9e2af",
        "layout_type": "grid",
        "is_preset": True,
        "tags": ["prioritization", "decision-making", "classic"],
        "config": {
            "max_items": None,
            "categories": [
                {
                    "id": "do",
                    "name": "Do First",
                    "name_zh": "\u7acb\u523b\u505a",
                    "icon": "\U0001f534",
                    "color": "#f38ba8",
                    "max_items": None,
                    "min_items": 0,
                    "sort_order": 0,
                    "priority_weight": 4,
                    # Q1: urgent + important — high/urgent priority AND due within 2 days
                    "accept_filter": {
                        "priority": ["urgent", "high"],
                        "due_date_within_days": 2,
                    },
                },
                {
                    "id": "delegate",
                    "name": "Delegate",
                    "name_zh": "\u59d4\u6d3e\u4ed6\u4eba",
                    "icon": "\U0001f7e0",
                    "color": "#fab387",
                    "max_items": None,
                    "min_items": 0,
                    "sort_order": 1,
                    "priority_weight": 1,
                    # Q3: urgent + not important — due within 2 days (any priority not caught by Q1)
                    "accept_filter": {"due_date_within_days": 2},
                },
                {
                    "id": "schedule",
                    "name": "Schedule",
                    "name_zh": "\u5b89\u6392\u6642\u9593",
                    "icon": "\U0001f535",
                    "color": "#89b4fa",
                    "max_items": None,
                    "min_items": 0,
                    "sort_order": 2,
                    "priority_weight": 3,
                    # Q2: not urgent + important — high/urgent priority but no imminent deadline
                    "accept_filter": {"priority": ["urgent", "high"]},
                },
                {
                    "id": "eliminate",
                    "name": "Eliminate",
                    "name_zh": "\u8003\u616e\u522a\u9664",
                    "icon": "\u26aa",
                    "color": "#a6adc8",
                    "max_items": None,
                    "min_items": 0,
                    "sort_order": 3,
                    "priority_weight": 0,
                    # Q4: not urgent + not important — everything else (catch-all)
                    "accept_filter": {},
                },
            ],
            "ordering": "category",
            "sequential_strict": False,
            "frog": {"enabled": False},
            "time_awareness": {"enabled": False, "mode": "none"},
            "review_cycle": {
                "morning_review": {
                    "enabled": True,
                    "default_time": "08:00",
                    "prompt_zh": "\u5206\u985e\u4eca\u65e5\u5f85\u8fa6\u5230\u56db\u500b\u8c61\u9650",  # noqa: E501
                },
                "evening_review": {
                    "enabled": True,
                    "default_time": "21:00",
                    "prompt_zh": "\u54ea\u4e9b\u61c9\u8a72\u522a\u9664\uff1f\u54ea\u4e9b\u53ef\u4ee5\u59d4\u6d3e\uff1f",  # noqa: E501
                },
                "weekly_review": {"enabled": False},
            },
            "completion_rule": {
                "mode": "weighted",
                "threshold": 0.7,
                "frog_required": False,
                "streak_tracking": True,
                "celebration": {"on_day_complete": "Matrix cleared!"},
            },
            "overflow": {
                "mode": "review_then_decide",
                "max_carry_days": 3,
                "stale_warning_days": 2,
            },
            "item_sources": {
                "taskflow": {
                    "enabled": True,
                    "auto_include_due_today": True,
                    "auto_include_overdue": True,
                },
                "finance": {"enabled": False},
                "invest": {"enabled": False},
                "briefing": {"enabled": False},
                "capture": {"enabled": False},
            },
            "ui_hints": {
                "show_numbers": False,
                "show_category_headers": True,
                "show_progress_bar": True,
                "show_time_column": False,
                "show_frog_badge": False,
                "empty_state_message_zh": "\u5c07\u5f85\u8fa6\u4e8b\u9805\u5206\u985e\u5230\u56db\u500b\u8c61\u9650\uff1a\u5148\u505a\u3001\u5b89\u6392\u3001\u59d4\u6d3e\u3001\u522a\u9664\u3002",  # noqa: E501
                "compact_mode": False,
            },
        },
    },
    # ======================== 6. Kanban Daily ========================
    {
        "slug": "kanban-daily",
        "name": "Daily Kanban",
        "name_zh": "\u6bcf\u65e5\u770b\u677f",
        "icon": "\U0001f4ca",
        "color": "#94e2d5",
        "layout_type": "kanban",
        "is_preset": True,
        "tags": ["visual", "flow", "agile"],
        "config": {
            "max_items": None,
            "categories": [
                {
                    "id": "todo",
                    "name": "To Do",
                    "name_zh": "\u5f85\u8fa6",
                    "icon": "\u25cb",
                    "color": "#a6adc8",
                    "max_items": None,
                    "min_items": 0,
                    "sort_order": 0,
                    "priority_weight": 1,
                },
                {
                    "id": "doing",
                    "name": "Doing",
                    "name_zh": "\u9032\u884c\u4e2d",
                    "icon": "\u25d1",
                    "color": "#89b4fa",
                    "max_items": 3,
                    "min_items": 0,
                    "sort_order": 1,
                    "priority_weight": 2,
                },
                {
                    "id": "done",
                    "name": "Done",
                    "name_zh": "\u5b8c\u6210",
                    "icon": "\u2713",
                    "color": "#a6e3a1",
                    "max_items": None,
                    "min_items": 0,
                    "sort_order": 2,
                    "priority_weight": 1,
                },
            ],
            "ordering": "category",
            "sequential_strict": False,
            "frog": {"enabled": False},
            "time_awareness": {"enabled": False, "mode": "none"},
            "review_cycle": {
                "morning_review": {
                    "enabled": True,
                    "default_time": "09:00",
                    "prompt_zh": "\u586b\u5165\u4eca\u65e5\u770b\u677f",
                },
                "evening_review": {
                    "enabled": True,
                    "default_time": "18:00",
                    "prompt_zh": "\u6e05\u7406\u770b\u677f\uff0c\u56de\u9867\u6d41\u901f",
                },
                "weekly_review": {"enabled": False},
            },
            "completion_rule": {
                "mode": "percentage",
                "threshold": 0.8,
                "frog_required": False,
                "streak_tracking": True,
                "celebration": {"on_day_complete": "Board cleared!"},
            },
            "overflow": {
                "mode": "carry_forward",
                "max_carry_days": None,
                "stale_warning_days": 3,
            },
            "item_sources": {
                "taskflow": {
                    "enabled": True,
                    "auto_include_due_today": True,
                    "auto_include_overdue": True,
                },
                "finance": {"enabled": False},
                "invest": {"enabled": False},
                "briefing": {"enabled": False},
                "capture": {"enabled": False},
            },
            "ui_hints": {
                "show_numbers": False,
                "show_category_headers": True,
                "show_progress_bar": True,
                "show_time_column": False,
                "show_frog_badge": False,
                "empty_state_message_zh": "\u628a\u4eca\u5929\u8981\u505a\u7684\u4e8b\u62c9\u9032\u770b\u677f\u3002\u9650\u5236\u300c\u9032\u884c\u4e2d\u300d\u4e0d\u8d85\u904e 3 \u4ef6\u3002",  # noqa: E501
                "compact_mode": False,
            },
        },
    },
    # ======================== 7. Pomodoro Technique ========================
    {
        "slug": "pomodoro",
        "name": "Pomodoro Technique",
        "name_zh": "\u756a\u8304\u9418\u5de5\u4f5c\u6cd5",
        "icon": "\U0001f345",
        "color": "#f38ba8",
        "layout_type": "list",
        "is_preset": True,
        "tags": ["focus", "time-management", "breaks"],
        "config": {
            "max_items": None,
            "categories": [],
            "ordering": "priority",
            "sequential_strict": False,
            "frog": {
                "enabled": True,
                "count": 1,
                "label": "Focus Task",
                "label_zh": "\u7126\u9ede\u4efb\u52d9",
                "icon": "\U0001f345",
                "auto_suggest": True,
                "suggest_criteria": {
                    "prefer_high_priority": True,
                    "prefer_dreaded": False,
                    "prefer_high_impact": True,
                },
                "must_do_first": True,
            },
            "time_awareness": {
                "enabled": True,
                "mode": "estimates",
                "day_start": "09:00",
                "day_end": "18:00",
                "slot_duration_minutes": 25,
                "include_breaks": True,
                "break_pattern": {"work_minutes": 25, "break_minutes": 5},
                "pomodoro": {
                    "work_minutes": 25,
                    "short_break": 5,
                    "long_break": 15,
                    "long_break_interval": 4,
                },
            },
            "review_cycle": {
                "morning_review": {
                    "enabled": True,
                    "default_time": "09:00",
                    "prompt_zh": "\u4f30\u7b97\u6bcf\u500b\u4efb\u52d9\u9700\u8981\u5e7e\u500b\u756a\u8304\u9418",  # noqa: E501
                },
                "evening_review": {
                    "enabled": True,
                    "default_time": "18:00",
                    "prompt_zh": "\u4eca\u65e5\u5b8c\u6210\u5e7e\u500b\u756a\u8304\u9418\uff1f\u4f30\u7b97\u6e96\u78ba\u55ce\uff1f",  # noqa: E501
                },
                "weekly_review": {"enabled": False},
            },
            "completion_rule": {
                "mode": "percentage",
                "threshold": 0.7,
                "frog_required": False,
                "streak_tracking": True,
                "celebration": {
                    "on_frog_done": "Focus task complete!",
                    "on_day_complete": "Great pomodoro session!",
                },
            },
            "overflow": {
                "mode": "carry_forward",
                "max_carry_days": None,
                "stale_warning_days": 3,
            },
            "item_sources": {
                "taskflow": {
                    "enabled": True,
                    "auto_include_due_today": True,
                    "auto_include_overdue": True,
                },
                "finance": {"enabled": False},
                "invest": {"enabled": False},
                "briefing": {"enabled": False},
                "capture": {"enabled": False},
            },
            "ui_hints": {
                "show_numbers": False,
                "show_category_headers": False,
                "show_progress_bar": True,
                "show_time_column": True,
                "show_frog_badge": True,
                "empty_state_message_zh": "\u52a0\u5165\u4efb\u52d9\uff0c\u4f30\u7b97\u756a\u8304\u9418\u6578\u91cf\uff0c\u958b\u59cb\u5c08\u6ce8\u3002",  # noqa: E501
                "compact_mode": False,
            },
        },
    },
]
