"""GitHub Copilot CLI entry."""

from __future__ import annotations

import re

from cli_rosetta.base import (
    AgentSpec,
    AutoApprove,
    CLIEntry,
    ExitBehavior,
    HeadlessSpec,
    HookSpec,
    InstructionSpec,
    MCPSpec,
    SkillSpec,
    ToolNameMap,
)

COPILOT_CLI = CLIEntry(
    name="copilot-cli",
    binary="copilot",
    display_name="GitHub Copilot CLI",
    vendor="github",
    config_dir="~/.copilot/",
    install_command="brew install copilot-cli",
    exit_behavior=ExitBehavior(key_sequence="C-c", repeat=1),
    idle_prompt=">",
    processing_indicators=(),
    headless=HeadlessSpec(
        prompt_flag="-p",
        output_format_flag="",
        cwd_flag="",
    ),
    auto_approve=AutoApprove(
        flag="--allow-all",
        aliases=("--yolo", "--allow-all-tools"),
    ),
    model_flag="--model",
    default_model="gpt-5.2",
    resume_flag="--resume",
    continue_flag="--continue",
    known_version="1.0.18",
    brew_package="copilot-cli",
    prompt_pattern=re.compile(r">"),
    process_names=frozenset({"copilot"}),
    # ── Configuration ecosystem ──
    mcp=MCPSpec(
        config_format="json",
        config_path="mcp-config.json",  # ~/.copilot/mcp-config.json
        config_key="mcpServers",
        supports_http=True,
        supports_stdio=True,
        http_url_key="url",
        env_in_config=True,
    ),
    skills=SkillSpec(
        dir_name="",  # Copilot CLI has no skill system
        file_name="",
        format="",
    ),
    hooks=HookSpec(
        config_path="",  # Copilot CLI has no hooks system
        config_format="",
        events=(),
    ),
    instructions=InstructionSpec(
        global_file="instructions.md",  # ~/.copilot/instructions.md
        project_file=".github/copilot-instructions.md",  # generated by `copilot init`
        rules_dir="",
    ),
    agents=AgentSpec(dir_name="", file_format=""),  # --agent flag exists but no dir convention
    # Copilot tool names (verified: --allow-tool docs + binary strings + headless output)
    tool_names=ToolNameMap(
        read="read",
        write="write",
        edit="edit",
        bash="shell",  # confirmed: --allow-tool='shell(git:*)'
        glob="glob",  # confirmed from binary strings
        grep="search",  # Copilot uses "search" for content search
        web_fetch="web_fetch",  # confirmed from headless tool list
        web_search="web_search",  # confirmed from headless tool list
        agent="",
        notebook_edit="",
    ),
)
