#!/usr/bin/env python3
"""
hook-observatory installer — auto-register hooks into Claude Code.

Usage:
    python3 install.py              # interactive install
    python3 install.py --uninstall  # remove hooks from settings.json
    python3 install.py --dry-run    # show what would happen
    python3 install.py --python /path/to/python3  # explicit Python path

What it does:
1. Detects (or accepts) Python interpreter path
2. Writes/updates dispatcher.py in ~/.claude/hooks/
3. Generates hook entries in ~/.claude/settings.json
4. Creates config.local.yaml from config.yaml if not exists
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

OBSERVATORY_ROOT = Path(__file__).resolve().parent
HANDLERS_DIR = OBSERVATORY_ROOT / "handlers"
CONFIG_EXAMPLE = OBSERVATORY_ROOT / "config.example.yaml"  # committed template
CONFIG_USER = OBSERVATORY_ROOT / "config.yaml"  # user config (gitignored)
CLAUDE_DIR = Path.home() / ".claude"
HOOKS_DIR = CLAUDE_DIR / "hooks"
SETTINGS_JSON = CLAUDE_DIR / "settings.json"
DISPATCHER_TARGET = HOOKS_DIR / "dispatcher.py"

# Dispatcher template — the thin shim
DISPATCHER_TEMPLATE = '''\
#!/usr/bin/env python3
"""
Unified hook dispatcher for Claude Code — thin shim.
Auto-generated by hook-observatory install.py. Do not edit manually.

Reads event_type from argv[1], stdin JSON, and delegates to
hook-observatory/handlers/ package via direct import (no subprocess).
"""

import os
import sys

# Add hook-observatory to import path
sys.path.insert(0, {observatory_path!r})


def main():
    event_type = sys.argv[1] if len(sys.argv) > 1 else ""
    raw_input = sys.stdin.read()

    from handlers import dispatch

    output = dispatch(event_type, raw_input)
    if output:
        sys.stdout.write(output)
        if not output.endswith("\\n"):
            sys.stdout.write("\\n")


if __name__ == "__main__":
    try:
        main()
    except Exception:
        # Fail-open: never crash, never block
        print("{{}}")
'''


# ---------------------------------------------------------------------------
# Config loader (minimal, no PyYAML dependency for installer)
# ---------------------------------------------------------------------------


def load_hook_timeouts() -> dict[str, int]:
    """Load hook timeouts from config.yaml (simple parser)."""
    defaults = {
        "PreToolUse": 20,
        "PostToolUse": 35,
        "Stop": 20,
        "Notification": 20,
        "SessionStart": 35,
        "SessionEnd": 20,
        "SubagentStart": 10,
        "SubagentStop": 120,
        "UserPromptSubmit": 20,
        "PreCompact": 10,
    }

    # Try to read from config
    for config_path in [CONFIG_USER, CONFIG_EXAMPLE]:
        if not config_path.is_file():
            continue
        text = config_path.read_text()
        in_timeouts = False
        for line in text.splitlines():
            stripped = line.strip()
            if "hook_timeouts:" in stripped:
                in_timeouts = True
                continue
            if in_timeouts:
                if not line.startswith(" ") and not line.startswith("\t"):
                    break  # left indent = exited block
                if ":" in stripped and not stripped.startswith("#"):
                    key, _, val = stripped.partition(":")
                    key = key.strip()
                    val = val.strip().split("#")[0].strip()
                    if key in defaults:
                        try:
                            defaults[key] = int(val)
                        except ValueError:
                            pass
        break  # use first found config

    return defaults


# ---------------------------------------------------------------------------
# Python detection
# ---------------------------------------------------------------------------


def detect_python() -> str:
    """Find a suitable Python 3.12+ interpreter."""
    candidates = [
        sys.executable,
        shutil.which("python3"),
        os.path.expanduser("~/.local/bin/python3"),
        "/opt/homebrew/bin/python3",
        "/usr/local/bin/python3",
        "/usr/bin/python3",
    ]

    for candidate in candidates:
        if candidate and os.path.isfile(candidate):
            return candidate

    return "python3"  # fallback, hope it's in PATH


# ---------------------------------------------------------------------------
# Settings.json manipulation
# ---------------------------------------------------------------------------


def read_settings() -> dict:
    """Read existing settings.json or return empty dict."""
    if SETTINGS_JSON.is_file():
        try:
            return json.loads(SETTINGS_JSON.read_text())
        except json.JSONDecodeError:
            print(f"  WARNING: {SETTINGS_JSON} has invalid JSON, backing up")
            backup = SETTINGS_JSON.with_suffix(".json.bak")
            shutil.copy2(SETTINGS_JSON, backup)
            return {}
    return {}


def generate_hook_entries(python_path: str) -> dict:
    """Generate the hooks section for settings.json."""
    timeouts = load_hook_timeouts()
    dispatcher = str(DISPATCHER_TARGET)

    hooks: dict = {}
    for event_type, timeout in timeouts.items():
        hooks[event_type] = [
            {
                "matcher": "",
                "hooks": [
                    {
                        "type": "command",
                        "command": f"{python_path} {dispatcher} {event_type}",
                        "timeout": timeout,
                    }
                ],
            }
        ]

    return hooks


def install_hooks(python_path: str, dry_run: bool = False) -> None:
    """Main installation logic."""
    print("hook-observatory installer")
    print("=" * 50)

    # 1. Detect Python
    print(f"\n[1/4] Python interpreter: {python_path}")

    # 2. Write dispatcher
    print(f"\n[2/4] Dispatcher → {DISPATCHER_TARGET}")
    dispatcher_content = DISPATCHER_TEMPLATE.format(observatory_path=str(OBSERVATORY_ROOT))

    if dry_run:
        print("  (dry-run) would write dispatcher.py")
    else:
        HOOKS_DIR.mkdir(parents=True, exist_ok=True)
        DISPATCHER_TARGET.write_text(dispatcher_content)
        os.chmod(DISPATCHER_TARGET, 0o755)
        print("  written")

    # 3. Update settings.json
    print(f"\n[3/4] Settings → {SETTINGS_JSON}")
    settings = read_settings()
    new_hooks = generate_hook_entries(python_path)

    existing_hooks = settings.get("hooks", {})
    if existing_hooks:
        # Show diff
        added = set(new_hooks.keys()) - set(existing_hooks.keys())
        updated = set(new_hooks.keys()) & set(existing_hooks.keys())
        if added:
            print(f"  + adding events: {', '.join(sorted(added))}")
        if updated:
            print(f"  ~ updating events: {', '.join(sorted(updated))}")
    else:
        print(f"  + adding {len(new_hooks)} event hooks")

    settings["hooks"] = new_hooks

    if dry_run:
        print("  (dry-run) would update settings.json")
    else:
        SETTINGS_JSON.parent.mkdir(parents=True, exist_ok=True)
        SETTINGS_JSON.write_text(json.dumps(settings, indent=2, ensure_ascii=False) + "\n")
        print("  written")

    # 4. Create config.yaml from example if needed
    print(f"\n[4/4] Config → {CONFIG_USER}")
    if CONFIG_USER.is_file():
        print("  config.yaml already exists, skipping")
    else:
        if dry_run:
            print("  (dry-run) would copy config.example.yaml → config.yaml")
        else:
            shutil.copy2(CONFIG_EXAMPLE, CONFIG_USER)
            print("  created from config.example.yaml (edit to customize)")

    # Summary
    print("\n" + "=" * 50)
    print("Installation complete!")
    print("\nNext steps:")
    print(f"  1. Edit {CONFIG_USER}")
    print("     - Enable/disable handlers")
    print("     - Set service URLs if using integrations")
    print("  2. Restart Claude Code to pick up new hooks")
    print(f"\nTo uninstall: python3 {__file__} --uninstall")


def uninstall_hooks(dry_run: bool = False) -> None:
    """Remove hook-observatory entries from settings.json."""
    print("hook-observatory uninstaller")
    print("=" * 50)

    # Remove hooks from settings.json
    if SETTINGS_JSON.is_file():
        settings = read_settings()
        if "hooks" in settings:
            if dry_run:
                print(f"  (dry-run) would remove hooks from {SETTINGS_JSON}")
            else:
                del settings["hooks"]
                SETTINGS_JSON.write_text(json.dumps(settings, indent=2, ensure_ascii=False) + "\n")
                print(f"  removed hooks from {SETTINGS_JSON}")
        else:
            print("  no hooks found in settings.json")

    # Remove dispatcher
    if DISPATCHER_TARGET.is_file():
        if dry_run:
            print(f"  (dry-run) would remove {DISPATCHER_TARGET}")
        else:
            DISPATCHER_TARGET.unlink()
            print(f"  removed {DISPATCHER_TARGET}")

    print("\nDone. Restart Claude Code to apply.")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def main():
    parser = argparse.ArgumentParser(description="Install hook-observatory into Claude Code")
    parser.add_argument(
        "--python",
        default=None,
        help="Python interpreter path (default: auto-detect)",
    )
    parser.add_argument(
        "--uninstall",
        action="store_true",
        help="Remove hooks from settings.json",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show what would happen without making changes",
    )
    args = parser.parse_args()

    if args.uninstall:
        uninstall_hooks(dry_run=args.dry_run)
    else:
        python_path = args.python or detect_python()
        install_hooks(python_path, dry_run=args.dry_run)


if __name__ == "__main__":
    main()
