import type { AppInfo } from '@/types'

export const APP_LIST: AppInfo[] = [
  {
    id: 'finance',
    name: '記帳理財',
    description: '支出追蹤、預算管理、訂閱分析',
    icon: '\uD83D\uDCB0',
    path: '/finance',
    color: '#a6e3a1',
    status: 'available',
  },
  {
    id: 'taskflow',
    name: '任務排程',
    description: '任務管理、派工系統、獎勵機制',
    icon: '\uD83D\uDCCB',
    path: '/taskflow',
    color: '#cba6f7',
    status: 'available',
  },
  {
    id: 'ideagraph',
    name: '靈感圖譜',
    description: '靈感捕捉、知識圖譜、連結探索',
    icon: '\uD83D\uDCA1',
    path: '/ideagraph',
    color: '#f9e2af',
    status: 'available',
  },
  {
    id: 'admin',
    name: '管理後台',
    description: '使用者管理、系統設定、審計紀錄',
    icon: '\u2699\uFE0F',
    path: '/admin',
    color: '#a6adc8',
    status: 'available',
  },
  {
    id: 'intelflow',
    name: '情報研究',
    description: '研究報告、語意搜尋、智能問答',
    icon: '\uD83D\uDD2C',
    path: '/intelflow',
    color: '#94e2d5',
    status: 'available',
  },
  {
    id: 'memvault',
    name: '記憶金庫',
    description: 'AI 記憶管理、語意搜尋、KAS 圖譜',
    icon: '\uD83E\uDDE0',
    path: '/memvault',
    color: '#bdd4fa',
    status: 'available',
  },
  {
    id: 'nodeflow',
    name: '事件流程',
    description: '視覺化事件流引擎、跨模組自動化',
    icon: '\u26A1',
    path: '/nodeflow',
    color: '#fab387',
    status: 'available',
  },
  {
    id: 'invest',
    name: '投資追蹤',
    description: '持倉管理、交易紀錄、損益分析',
    icon: '\uD83D\uDCC8',
    path: '/invest',
    color: '#f38ba8',
    status: 'available',
  },
  {
    id: 'notification',
    name: '通知管理',
    description: '推播發送、通知歷史、頻道管理',
    icon: '\uD83D\uDD14',
    path: '/notification',
    color: '#cba6f7',
    status: 'available',
  },
  {
    id: 'capture',
    name: 'Capture Console',
    description: 'Quick capture + AI enrichment console',
    icon: '\u26A1',
    path: '/capture',
    color: '#f9e2af',
    status: 'available',
  },
  {
    id: 'dailyos',
    name: '每日規劃',
    description: '每日計劃、方法論管理、儀式循環引擎',
    icon: '📅',
    path: '/dailyos',
    color: '#cba6f7',
    status: 'available',
  },
  {
    id: 'skillpath',
    name: '技能路徑',
    description: '技能樹、學習路徑、成長規劃',
    icon: '🌳',
    path: '/skillpath',
    color: '#fab387',
    status: 'coming-soon',
  },
  {
    id: 'workpool',
    name: '資源管理',
    description: '資源排程、人力配置、容量管理',
    icon: '📦',
    path: '/workpool',
    color: '#f2cdcd',
    status: 'coming-soon',
  },
  {
    id: 'matchcore',
    name: '匹配引擎',
    description: '人才匹配、專案配對、智慧推薦',
    icon: '🔗',
    path: '/matchcore',
    color: '#eba0ac',
    status: 'coming-soon',
  },
  {
    id: 'briefing',
    name: '每日簡報',
    description: '多 AI 交叉辯論、每日情報摘要、領域追蹤',
    icon: '\uD83D\uDCF0',
    path: '/briefing',
    color: '#c9a962',
    status: 'available',
  },
  {
    id: 'agent-vista',
    name: 'Agent Vista',
    description: '像素風虛擬辦公室 — CLI Agent 即時視覺化',
    icon: '🎮',
    path: '/agent-vista',
    color: '#b4befe',
    status: 'external',
    externalUrl: '/apps/vista/',
  },
  {
    id: 'filebrowser',
    name: '檔案管理',
    description: '遠端檔案瀏覽、上傳下載、線上編輯',
    icon: '📁',
    path: '/filebrowser',
    color: '#f5c2e7',
    status: 'external',
    externalUrl: '/apps/files/',
  },
  {
    id: 'hook-observatory',
    name: 'Hook 監控台',
    description: 'Claude Code Hook 事件監控、統計分析',
    icon: '📡',
    path: '/hook-observatory',
    color: '#89b4fa',
    status: 'external',
    externalUrl: '/apps/hook/',
  },
  {
    id: 'tmux-webui',
    name: '終端遙控',
    description: 'tmux 遠端操控、多窗格管理、觸控優化',
    icon: '🖥️',
    path: '/tmux-webui',
    color: '#cba6f7',
    status: 'external',
    externalUrl: '/apps/tmux/',
  },
  {
    id: 'system-monitor',
    name: '系統監控',
    description: '硬體狀態、壓力警報、歷史報告',
    icon: '📊',
    path: '/system-monitor',
    color: '#a6e3a1',
    status: 'external',
    externalUrl: '/apps/sysmon/',
  },
  {
    id: 'sentinel',
    name: '服務哨兵',
    description: '健康監測、自動修復、狀態總覽',
    icon: '🛡️',
    path: '/sentinel',
    color: '#74c7ec',
    status: 'external',
    externalUrl: '/apps/sentinel/',
  },
  {
    id: 'auto-survey',
    name: '自動填表',
    description: 'SurveyCake 自動填表、人員管理、排程通知',
    icon: '📋',
    path: '/auto-survey',
    color: '#b4befe',
    status: 'external',
    externalUrl: '/apps/survey/',
  },
]
