import type { AppInfo } from "@/types";

export const APP_LIST: AppInfo[] = [
  {
    id: "finance",
    name: "記帳理財",
    description: "支出追蹤、預算管理、訂閱分析",
    icon: "\uD83D\uDCB0",
    path: "/finance",
    color: "#a6e3a1",
    status: "available",
  },
  {
    id: "taskflow",
    name: "任務排程",
    description: "任務管理、派工系統、獎勵機制",
    icon: "\uD83D\uDCCB",
    path: "/taskflow",
    color: "#cba6f7",
    status: "available",
  },
  {
    id: "ideagraph",
    name: "靈感圖譜",
    description: "靈感捕捉、知識圖譜、連結探索",
    icon: "\uD83D\uDCA1",
    path: "/ideagraph",
    color: "#f9e2af",
    status: "available",
  },
  {
    id: "admin",
    name: "管理後台",
    description: "使用者管理、系統設定、審計紀錄",
    icon: "\u2699\uFE0F",
    path: "/admin",
    color: "#a6adc8",
    status: "available",
  },
  {
    id: "intelflow",
    name: "情報研究",
    description: "研究報告、語意搜尋、智能問答",
    icon: "\uD83D\uDD2C",
    path: "/intelflow",
    color: "#94e2d5",
    status: "available",
  },
  {
    id: "memvault",
    name: "記憶金庫",
    description: "AI 記憶管理、語意搜尋、KAS 圖譜",
    icon: "\uD83E\uDDE0",
    path: "/memvault",
    color: "#bdd4fa",
    status: "available",
  },
  {
    id: "skillpath",
    name: "技能路徑",
    description: "技能樹、學習路徑、成長規劃",
    icon: "🌳",
    path: "/skillpath",
    color: "#fab387",
    status: "coming-soon",
  },
  {
    id: "workpool",
    name: "資源管理",
    description: "資源排程、人力配置、容量管理",
    icon: "📦",
    path: "/workpool",
    color: "#f2cdcd",
    status: "coming-soon",
  },
  {
    id: "matchcore",
    name: "匹配引擎",
    description: "人才匹配、專案配對、智慧推薦",
    icon: "🔗",
    path: "/matchcore",
    color: "#eba0ac",
    status: "coming-soon",
  },
  {
    id: "hook-observatory",
    name: "Hook 監控台",
    description: "Claude Code Hook 事件監控、統計分析",
    icon: "📡",
    path: "/hook-observatory",
    color: "#89b4fa",
    status: "external",
    externalUrl: "/v2/apps/hook/",
  },
];
