import type { AppInfo } from '@/types'

export const APP_LIST: AppInfo[] = [
  {
    id: 'finance',
    name: '記帳理財',
    description: '支出追蹤、預算管理、訂閱分析',
    icon: '\uD83D\uDCB0',
    path: '/finance',
    color: '#a6e3a1',
    status: 'available',
  },
  {
    id: 'taskflow',
    name: '任務排程',
    description: '任務管理、派工系統、獎勵機制',
    icon: '\uD83D\uDCCB',
    path: '/taskflow',
    color: '#cba6f7',
    status: 'available',
  },
  {
    id: 'ideagraph',
    name: '靈感圖譜',
    description: '靈感捕捉、知識圖譜、連結探索',
    icon: '\uD83D\uDCA1',
    path: '/ideagraph',
    color: '#f9e2af',
    status: 'coming-soon',
  },
  {
    id: 'admin',
    name: '管理後台',
    description: '使用者管理、系統設定、審計紀錄',
    icon: '\u2699\uFE0F',
    path: '/admin',
    color: '#a6adc8',
    status: 'available',
  },
  {
    id: 'intelflow',
    name: '情報研究',
    description: '研究報告、語意搜尋、智能問答',
    icon: '\uD83D\uDD2C',
    path: '/intelflow',
    color: '#94e2d5',
    status: 'available',
  },
  {
    id: 'memvault',
    name: '記憶金庫',
    description: 'AI 記憶管理、語意搜尋、KAS 圖譜',
    icon: '\uD83E\uDDE0',
    path: '/memvault',
    color: '#bdd4fa',
    status: 'available',
  },
  {
    id: 'nodeflow',
    name: '事件流程',
    description: '視覺化事件流引擎、跨模組自動化',
    icon: '\u26A1',
    path: '/nodeflow',
    color: '#fab387',
    status: 'available',
  },
  {
    id: 'invest',
    name: '投資追蹤',
    description: '持倉管理、交易紀錄、損益分析',
    icon: '\uD83D\uDCC8',
    path: '/invest',
    color: '#f38ba8',
    status: 'available',
  },
  {
    id: 'notification',
    name: '通知管理',
    description: '推播發送、通知歷史、頻道管理',
    icon: '\uD83D\uDD14',
    path: '/notification',
    color: '#cba6f7',
    status: 'available',
  },
  {
    id: 'capture',
    name: 'Capture Console',
    description: 'Quick capture + AI enrichment console',
    icon: '\u26A1',
    path: '/capture',
    color: '#f9e2af',
    status: 'available',
  },
  {
    id: 'dailyos',
    name: '每日規劃',
    description: '每日計劃、方法論管理、儀式循環引擎',
    icon: '📅',
    path: '/dailyos',
    color: '#cba6f7',
    status: 'available',
  },
  {
    id: 'skillpath',
    name: '技能路徑',
    description: '技能樹、學習路徑、成長規劃',
    icon: '🌳',
    path: '/skillpath',
    color: '#fab387',
    status: 'coming-soon',
  },
  {
    id: 'workpool',
    name: '資源管理',
    description: '資源排程、人力配置、容量管理',
    icon: '📦',
    path: '/workpool',
    color: '#f2cdcd',
    status: 'coming-soon',
  },
  {
    id: 'matchcore',
    name: '匹配引擎',
    description: '人才匹配、專案配對、智慧推薦',
    icon: '🔗',
    path: '/matchcore',
    color: '#eba0ac',
    status: 'coming-soon',
  },
  {
    id: 'briefing',
    name: '每日簡報',
    description: '多 AI 交叉辯論、每日情報摘要、領域追蹤',
    icon: '\uD83D\uDCF0',
    path: '/briefing',
    color: '#c9a962',
    status: 'available',
  },
  {
    id: 'paper',
    name: '論文研究',
    description: '學術論文管理、自動摘要、研究管線',
    icon: '📄',
    path: '/paper',
    color: '#89b4fa',
    status: 'available',
  },
  {
    id: 'docvault',
    name: '文件知識庫',
    description: '文件問答、語意搜尋、引用追蹤、領域 Profile',
    icon: '📚',
    path: '/docvault',
    color: '#74c7ec',
    status: 'available',
  },
  {
    id: 'agent-metrics',
    name: 'Agent 儀表板',
    description: 'LLM 用量追蹤、配額監控、模型成本分析',
    icon: '📈',
    path: '/agent-metrics',
    color: '#f38ba8',
    status: 'external',
    externalUrl: '/apps/agent-metrics/',
  },
  {
    id: 'agent-vista',
    name: 'Agent Vista',
    description: '像素風虛擬辦公室 — CLI Agent 即時視覺化',
    icon: '🎮',
    path: '/agent-vista',
    color: '#b4befe',
    status: 'external',
    externalUrl: '/apps/vista/',
  },
  {
    id: 'filebrowser',
    name: '檔案管理',
    description: '遠端檔案瀏覽、上傳下載、線上編輯',
    icon: '📁',
    path: '/filebrowser',
    color: '#f5c2e7',
    status: 'external',
    externalUrl: '/apps/files/',
  },
  {
    id: 'hook-observatory',
    name: 'Hook 監控台',
    description: 'Claude Code Hook 事件監控、統計分析',
    icon: '📡',
    path: '/hook-observatory',
    color: '#89b4fa',
    status: 'external',
    externalUrl: '/apps/hook/',
  },
  {
    id: 'session-channel',
    name: 'Session 頻道',
    description: '跨 Session 即時通訊、Redis Streams 訊息監控',
    icon: '📢',
    path: '/session-channel',
    color: '#74c7ec',
    status: 'external',
    externalUrl: '/apps/channel/',
  },
  {
    id: 'tmux-webui',
    name: '終端遙控',
    description: 'tmux 遠端操控、多窗格管理、觸控優化',
    icon: '🖥️',
    path: '/tmux-webui',
    color: '#cba6f7',
    status: 'external',
    externalUrl: '/apps/tmux/',
  },
  {
    id: 'system-monitor',
    name: '系統監控',
    description: '硬體狀態、壓力警報、歷史報告',
    icon: '📊',
    path: '/system-monitor',
    color: '#a6e3a1',
    status: 'external',
    externalUrl: '/apps/sysmon/',
  },
  {
    id: 'sentinel',
    name: '服務哨兵',
    description: '健康監測、自動修復、狀態總覽',
    icon: '🛡️',
    path: '/sentinel',
    color: '#74c7ec',
    status: 'external',
    externalUrl: '/apps/sentinel/',
  },
  {
    id: 'auto-survey',
    name: '自動填表',
    description: 'SurveyCake 自動填表、人員管理、排程通知',
    icon: '📋',
    path: '/auto-survey',
    color: '#b4befe',
    status: 'external',
    externalUrl: '/apps/survey/',
  },
  {
    id: 'anvil',
    name: '技能鍛造',
    description: 'Skill 生命週期管理、結構檢查、評估平台',
    icon: '🔨',
    path: '/anvil',
    color: '#fab387',
    status: 'available',
  },
  {
    id: 'scheduler',
    name: '排程管理',
    description: '定時任務排程、執行紀錄、Web UI 管理',
    icon: '\u23F0',
    path: '/scheduler',
    color: '#89dceb',
    status: 'external',
    externalUrl: '/apps/scheduler/',
  },
  {
    id: 'voice-center',
    name: '語音中心',
    description: '語音喚醒、STT 轉錄、Client/Server 雙路徑切換',
    icon: '🎙️',
    path: '/voice-center',
    color: '#f5c2e7',
    status: 'external',
    externalUrl: '/apps/voice/',
  },
  {
    id: 'ocr',
    name: '文字辨識',
    description: 'Apple Vision OCR、圖片 PDF 文字擷取、多引擎策略',
    icon: '👁️',
    path: '/ocr',
    color: '#89b4fa',
    status: 'external',
    externalUrl: '/apps/ocr/',
  },
  {
    id: 'mlt-editor',
    name: '剪輯時間軸',
    description: 'MLT 專案時間軸編輯器',
    icon: '🎬',
    path: '/mlt-editor',
    color: '#fab387',
    status: 'external',
    externalUrl: '/apps/mlt-editor/',
  },
  {
    id: 'tmux-as-bridge',
    name: 'tmux as bridge',
    description: 'tmux 三個月堆疊紀錄影片 · 從狀態列到多 agent 編排',
    icon: '📼',
    path: '/tmux-as-bridge',
    color: '#41ff97',
    status: 'external',
    externalUrl: '/apps/tmux-as-bridge/',
  },
  {
    id: 'toolbox',
    name: '工具箱',
    description: '獨立靜態網頁小工具集合 — SRT 修正、FSM 儀表板、PWA Debug…',
    icon: '🧰',
    path: '/toolbox',
    color: '#89dceb',
    status: 'external',
    externalUrl: '/toolbox',
  },
]
