"""migrate briefing embedding columns 768d → 1024d for Qwen3-Embedding-0.6B

Alters intelflow.briefings and intelflow.briefing_entries embedding columns
from vector(768) to vector(1024). Existing 768d embeddings are nulled out
(will be re-generated by the re-embed script).

Revision ID: e1f2g3h4i5j6
Revises: d0e1f2g3h4i5
Create Date: 2026-03-10
"""

from alembic import op

revision = "e1f2g3h4i5j6"
down_revision = "d0e1f2g3h4i5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Drop HNSW indexes that reference the old dimension
    op.execute("DROP INDEX IF EXISTS intelflow.idx_briefing_embedding")
    op.execute("DROP INDEX IF EXISTS intelflow.idx_be_embedding")

    # Null out old 768d embeddings (incompatible with new dimension)
    op.execute("UPDATE intelflow.briefings SET embedding = NULL WHERE embedding IS NOT NULL")
    op.execute("UPDATE intelflow.briefing_entries SET embedding = NULL WHERE embedding IS NOT NULL")

    # Alter column type from vector(768) to vector(1024)
    op.execute("ALTER TABLE intelflow.briefings ALTER COLUMN embedding TYPE vector(1024)")
    op.execute("ALTER TABLE intelflow.briefing_entries ALTER COLUMN embedding TYPE vector(1024)")

    # Recreate HNSW indexes with new dimension
    op.execute("""
        CREATE INDEX idx_briefing_embedding ON intelflow.briefings
        USING hnsw (embedding vector_cosine_ops)
        WITH (m = 16, ef_construction = 64)
    """)
    op.execute("""
        CREATE INDEX idx_be_embedding ON intelflow.briefing_entries
        USING hnsw (embedding vector_cosine_ops)
        WITH (m = 16, ef_construction = 64)
    """)


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS intelflow.idx_briefing_embedding")
    op.execute("DROP INDEX IF EXISTS intelflow.idx_be_embedding")
    op.execute("UPDATE intelflow.briefings SET embedding = NULL WHERE embedding IS NOT NULL")
    op.execute("UPDATE intelflow.briefing_entries SET embedding = NULL WHERE embedding IS NOT NULL")
    op.execute("ALTER TABLE intelflow.briefings ALTER COLUMN embedding TYPE vector(768)")
    op.execute("ALTER TABLE intelflow.briefing_entries ALTER COLUMN embedding TYPE vector(768)")
    op.execute("""
        CREATE INDEX idx_briefing_embedding ON intelflow.briefings
        USING hnsw (embedding vector_cosine_ops)
        WITH (m = 16, ef_construction = 64)
    """)
    op.execute("""
        CREATE INDEX idx_be_embedding ON intelflow.briefing_entries
        USING hnsw (embedding vector_cosine_ops)
        WITH (m = 16, ef_construction = 64)
    """)
