// Code generated by libs/go-port-registry/cmd/gen — DO NOT EDIT.
// Source: shared/schemas/port_registry.yaml
// Run `go generate ./...` from libs/go-port-registry to regenerate.

package portregistry

// Host is the bind address shared by every Workshop-managed service.
const Host = "127.0.0.1"

// Ports lists every service in registry order.
var Ports = []ServicePort{
	{Name: "core", Port: 10000, Group: "core", HealthPath: "/health", EnvVar: "CORE_API_URL", NginxPath: "", Optional: false},
	{Name: "paper", Port: 10010, Group: "core", HealthPath: "/health", EnvVar: "PAPER_SVC_URL", NginxPath: "/api/paper/", Optional: false},
	{Name: "intelflow", Port: 10011, Group: "core", HealthPath: "/health", EnvVar: "INTELFLOW_SVC_URL", NginxPath: "/api/intelflow/", Optional: false},
	{Name: "invest", Port: 10012, Group: "core", HealthPath: "/health", EnvVar: "INVEST_SVC_URL", NginxPath: "/api/invest/", Optional: false},
	{Name: "hook-observatory", Port: 10100, Group: "station-infra", HealthPath: "/", EnvVar: "HOOK_OBS_URL", NginxPath: "/apps/hook/", Optional: false},
	{Name: "session-channel", Port: 10101, Group: "station-infra", HealthPath: "/health", EnvVar: "SESSION_CHANNEL_URL", NginxPath: "/apps/channel/", Optional: false},
	{Name: "system-monitor", Port: 10102, Group: "station-infra", HealthPath: "/", EnvVar: "SYSTEM_MONITOR_URL", NginxPath: "/apps/sysmon/", Optional: false},
	{Name: "agent-metrics", Port: 10103, Group: "station-infra", HealthPath: "/health", EnvVar: "AGENT_METRICS_URL", NginxPath: "/apps/agent-metrics/", Optional: false},
	{Name: "capture-console", Port: 10104, Group: "station-infra", HealthPath: "/docs", EnvVar: "CAPTURE_CONSOLE_URL", NginxPath: "/apps/capture/", Optional: false},
	{Name: "tmux-webui", Port: 10105, Group: "station-infra", HealthPath: "/", EnvVar: "TMUX_WEBUI_URL", NginxPath: "/apps/tmux/", Optional: false},
	{Name: "sentinel", Port: 4101, Group: "station-infra", HealthPath: "/api/sentinel/health", EnvVar: "SENTINEL_URL", NginxPath: "/apps/sentinel/", Optional: false},
	{Name: "fleet", Port: 10106, Group: "station-infra", HealthPath: "/health", EnvVar: "FLEET_URL", NginxPath: "/apps/fleet/", Optional: false},
	{Name: "stt", Port: 10200, Group: "station-ai", HealthPath: "/health", EnvVar: "STT_URL", NginxPath: "", Optional: true},
	{Name: "tts", Port: 10201, Group: "station-ai", HealthPath: "/health", EnvVar: "TTS_URL", NginxPath: "", Optional: true},
	{Name: "ocr", Port: 10202, Group: "station-ai", HealthPath: "/health", EnvVar: "OCR_URL", NginxPath: "", Optional: true},
	{Name: "vision", Port: 10203, Group: "station-ai", HealthPath: "/health", EnvVar: "VISION_URL", NginxPath: "", Optional: true},
	{Name: "voice-gateway", Port: 10204, Group: "station-ai", HealthPath: "/health", EnvVar: "VOICE_GATEWAY_URL", NginxPath: "/apps/voice/", Optional: true},
	{Name: "translate", Port: 10205, Group: "station-ai", HealthPath: "/health", EnvVar: "TRANSLATE_URL", NginxPath: "", Optional: true},
	{Name: "video-edit", Port: 10206, Group: "station-ai", HealthPath: "/health", EnvVar: "VIDEO_EDIT_URL", NginxPath: "/apps/mlt-editor/", Optional: false},
	{Name: "agent-vista", Port: 10207, Group: "station-ai", HealthPath: "/", EnvVar: "AGENT_VISTA_URL", NginxPath: "/apps/vista/", Optional: false},
	{Name: "remote-node", Port: 10208, Group: "station-ai", HealthPath: "/health", EnvVar: "REMOTE_NODE_URL", NginxPath: "", Optional: true},
	{Name: "auto-survey", Port: 10300, Group: "station-biz", HealthPath: "/api/people", EnvVar: "AUTO_SURVEY_URL", NginxPath: "/apps/survey/", Optional: false},
	{Name: "anvil", Port: 10301, Group: "station-biz", HealthPath: "/docs", EnvVar: "ANVIL_URL", NginxPath: "/apps/anvil/", Optional: false},
	{Name: "blog", Port: 10302, Group: "station-biz", HealthPath: "/zh/", EnvVar: "BLOG_URL", NginxPath: "", Optional: false},
	{Name: "workbench", Port: 10500, Group: "frontend", HealthPath: "", EnvVar: "", NginxPath: "", Optional: false},
	{Name: "cronicle", Port: 4105, Group: "third-party", HealthPath: "/api/app/ping", EnvVar: "", NginxPath: "/apps/scheduler/", Optional: false},
	{Name: "litellm", Port: 4000, Group: "third-party", HealthPath: "/health/liveliness", EnvVar: "", NginxPath: "", Optional: false},
	{Name: "ccr", Port: 3456, Group: "third-party", HealthPath: "/", EnvVar: "", NginxPath: "", Optional: false},
	{Name: "mcpproxy", Port: 8808, Group: "third-party", HealthPath: "/health", EnvVar: "", NginxPath: "", Optional: false},
	{Name: "nginx", Port: 8080, Group: "third-party", HealthPath: "/health", EnvVar: "", NginxPath: "", Optional: false},
	{Name: "postgres", Port: 5432, Group: "docker", HealthPath: "", EnvVar: "", NginxPath: "", Optional: false},
	{Name: "redis", Port: 6379, Group: "docker", HealthPath: "", EnvVar: "", NginxPath: "", Optional: false},
	{Name: "qdrant", Port: 6333, Group: "docker", HealthPath: "/healthz", EnvVar: "", NginxPath: "", Optional: false},
	{Name: "rustfs", Port: 9000, Group: "docker", HealthPath: "/", EnvVar: "", NginxPath: "", Optional: false},
	{Name: "filebrowser", Port: 8850, Group: "docker", HealthPath: "/apps/files/health", EnvVar: "", NginxPath: "", Optional: false},
	{Name: "bark", Port: 8090, Group: "docker", HealthPath: "/ping", EnvVar: "", NginxPath: "", Optional: false},
	{Name: "lgtm", Port: 3100, Group: "docker", HealthPath: "/api/health", EnvVar: "", NginxPath: "", Optional: true},
}
